import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '..', 'outputs');

export function formatAndSave(results, { handle, niche, timestamp }) {
  mkdirSync(OUTPUT_DIR, { recursive: true });

  const slug = (handle || niche || 'output').replace(/[@\s]/g, '').toLowerCase();
  const ts = timestamp || new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const baseName = `${slug}_${ts}`;

  const markdown = buildMarkdown(results, { handle, niche });
  const mdPath = join(OUTPUT_DIR, `${baseName}.md`);
  writeFileSync(mdPath, markdown, 'utf8');

  const jsonPath = join(OUTPUT_DIR, `${baseName}.json`);
  writeFileSync(jsonPath, JSON.stringify({ handle, niche, timestamp: ts, results }, null, 2), 'utf8');

  return { mdPath, jsonPath };
}

function buildMarkdown(results, { handle, niche }) {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const lines = [
    `# MonetizeStudio Content Strategy`,
    `**Client:** ${handle || 'N/A'} | **Niche:** ${niche || 'N/A'} | **Date:** ${date}`,
    '',
    '---',
    '',
  ];

  for (const result of results) {
    if (!result) continue;

    const agentName = result.agent || 'Agent';
    lines.push(`## ${agentName}`);
    lines.push('');

    if (result.handle) lines.push(`> **Profile:** ${result.handle}`);
    if (result.niche) lines.push(`> **Niche:** ${result.niche}`);
    if (result.product) lines.push(`> **Product:** ${result.product} — $${result.price}`);
    if (result.idea) lines.push(`> **Script for:** "${result.idea}" (${result.platform} / ${result.stage})`);
    lines.push('');

    lines.push(result.output || '_No output_');
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push(`_Generated by MonetizeStudio Content Director on ${date}_`);
  return lines.join('\n');
}

export function printSection(title, content) {
  const bar = '═'.repeat(60);
  console.log(`\n${bar}`);
  console.log(`  ${title.toUpperCase()}`);
  console.log(bar);
  console.log(content);
}
